"$schema" = 'https://starship.rs/config-schema.json'
# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

[directory]
style = "bold green"
truncate_to_repo = false
