"$schema" = 'https://starship.rs/config-schema.json'
# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

[hostname]
ssh_only = true
format = "[$hostname]($style) "
style = "bold blue"
disabled = false

[directory]
style = "bold green"
truncate_to_repo = false
